### ISSUE TITLE
Drop Hexate dependency

### ISSUE THREAD

**Issue by josevalim** [chvanikoff/apns4ex#11]
You seem to use `Hexate.encode` and `Hexate.decode` but both functions already exist in Elixir via `Base.encode16` and `Base.decode16`. Maybe you can drop this dependency?

**Comment by chvanikoff** [comment]
@josevalim thank you for the suggestion, when I created initial version of the library (about a year ago), I didn't found suitable function at Elixir core. I'll try it today.

**Comment by chvanikoff** [comment]
Works fine, I've replaced Hexate with Base, thanks!
