### ISSUE TITLE
The debug message about Reconnect is wrong

### ISSUE THREAD

**Issue by zepplock** [chvanikoff/apns4ex#13]
If I have my reconnect timeout sent to X seconds I see 1000x of the value in . For example for 120 seconds: `[debug] [APNS] Feedback socket was closed. Reconnect in 1200000s.`

I believe the offending lien is: https://github.com/chvanikoff/apns4ex/blob/9e205654462d557c015397f92524ffd6c052d1d3/lib/apns/worker.ex#L82

Can you quick fix next time you make a release or do you want a PR?

**Comment by chvanikoff** [comment]
Sure you can send PR and I'll merge it to the master but next version release is not planned yet.
Thank you!

**Comment by zepplock** [comment]
He ere you go https://github.com/chvanikoff/apns4ex/pull/14

**Comment by chvanikoff** [comment]
Merged, thanks!

**Comment by zepplock** [comment]
Тебе спасибо, Роман!

**Comment by chvanikoff** [comment]
:smile:
