### ISSUE TITLE
Support category field

### ISSUE THREAD

**Issue by jnicklas** [chvanikoff/apns4ex#17]
Messages should support sending a category field as specified by Apple: 

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW2

See table 3-1

It seems that there is no support for this right now, right? Should we send a PR for this?

**Comment by chvanikoff** [comment]
Hi @jnicklas , yes I've seen it and this is currently not implemented. It was in my plan for one of the next versions. Surely you can send PR if you can't wait to see it in the library :smile:
