### ISSUE TITLE
Resend notifications when error is received

### ISSUE THREAD

**Issue by Linuus** [chvanikoff/apns4ex#29]
Hi!

I'm investigating why a lot of our push messages aren't delivered.

When reading here:
https://developer.apple.com/library/ios/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG44

Is states that 
"If you get six bytes back, that's an error response that you can check for the response code and the ID of the notification that caused the error. **You'll need to send every notification following that one again.**"

So, I believe that our issue is that we send some notifications, hit a bad token and all subsequent notifications are discarded by Apple.

As far as I can see this isn't handled by apns4ex. Is that correct?
If it isn't handled by apns4ex, how are you supposed to tackle this issue?

Any input here is very welcome since I am a bit lost at the moment... :)

cc @ramhoj

**Comment by Linuus** [comment]
I've been looking through the apns4erl codebase and I found that they actually support this:
See: https://github.com/inaka/apns4erl/pull/39/files

So, we need to implement something similar. We'll take a stab at it and send a PR if we manage to get something useful working.

**Comment by zepplock** [comment]
Thanks!
