### ISSUE TITLE
Allow APNS token from feedback to be encoded with lowercase

### ISSUE THREAD

**Issue by ramhoj** [chvanikoff/apns4ex#30]
The feedback module gets called with an uppercase representation of the hex APNS token (https://github.com/chvanikoff/apns4ex/blob/master/lib/apns/worker.ex#L122). It would be nice to allow the user to configure this.

``` elixir
config :apns,
  callback_module:    APNS.Callback,
  token_case: :lower # defaults to :upper,
  …
```

Would you consider a PR to address this?

**Comment by zepplock** [comment]
Yes, please.

**Comment by ramhoj** [comment]
Closing very old issue.
