### ISSUE TITLE
Apns HTTP2 support

### ISSUE THREAD

**Issue by ghost** [chvanikoff/apns4ex#55]
I would like to use HTTP2 endpoint of APNS, are you planning to update the lib and use the apns4erl v2 or should I start my own lib?

**Comment by zepplock** [comment]
I have no plans to add HTTPS2 at this point. I think https://github.com/codedge-llc/pigeon does HTTP2.

**Comment by zepplock** [comment]
@chvanikoff any plans for HTTP2?

**Comment by ghost** [comment]
pigeon and https://github.com/codedge-llc/kadabra are `Very much a work in progress`. That's why I was asking.
