### ISSUE TITLE
SSL validation failure

### ISSUE THREAD

**Issue by kroucis** [chvanikoff/apns4ex#8]
When attempting to connect to APNS using apns4ex v0.0.6, the connection fails with an error

```
[error] [APNS] failed to connect gateway.sandbox.push.apple.com:2195, reason given: {:options, {:password, "foobar1"}}
[error] [APNS] failed to connect gateway.sandbox.push.apple.com:2195, reason given: {:options, {:password, "foobar1"}}
[error] [APNS] failed to connect gateway.sandbox.push.apple.com:2195, reason given: {:options, {:password, "foobar1"}}
[error] GenServer #PID<0.339.0> terminating
```

However, this is the correct password as a call to `openssl s_client -connect gateway.sdbox.push.apple.com:2195 -cert ARootLevelCert.pem -key ARootLevelKey.pem -pass pass:foobar1` succeeds. No combination of certificate, key, and password generates a connection to APNS.

Below is the current configuration for the apns service:

```
config :apns,
  certfile:         "ARootLevelCert.pem",
  keyfile:          "ARootLevelKey.pem",
  cert_password:    "foobar1"
```

**Comment by kroucis** [comment]
The encoding for my certificate/key was incorrect. For proper certificate/key setup, see [this StackOverflow article](http://stackoverflow.com/questions/1762555/creating-pem-file-for-apns).

**Comment by chvanikoff** [comment]
Glad to see you resolved this problem :+1:
