### ISSUE TITLE
Callback module should receive a `completed/1` call.

### ISSUE THREAD

**Issue by kroucis** [chvanikoff/apns4ex#9]
In the case where there are hundreds, thousands, or even millions of messages being pushed, the APNS service may need to be alive for a long while. In order to shut the service down on-demand, a `finished/1` or `completed/1` callback would be very useful once the service has finished pushing all messages. The single argument to this function would be the pid of the APNS service. This functionality would help to facilitate integrity checks for the messages, and allow for spin-down of the APNS service when pushing is finished.
An example implementation that helps to illustrate the point is below:

``` elixir
defmodule MyFeedback do
  def completed(apnsPID) do
    APNS.stop(apnsPID)
  end
end
```

**Comment by chvanikoff** [comment]
I don't think apns4ex needs it - we don't have any queue in place and it's not clear to me why to stop the server and on what trigger.
By the way for millions of PNs I personally use worker pool at higher application level and am considering it out of the box.

**Comment by chvanikoff** [comment]
@kroucis ok from you comment in another issue I understood your case but it still not clear to me why to stop the service? Also I'd like to mention pooling your workers would be good idea and you can also add transaction where you will stop server on commit if you want to.

**Comment by kroucis** [comment]
Thanks for looking into this! It looks like apns4ex is really built for a different use-case than I am currently considering. I will likely be moving to a system closer to what you describe: a worker pool and manager that manages the workers and the apns4ex service(s) associated with those workers. Thanks all the same!
